---
- hosts: localhost 
  name: vCenter Configuration 
  collections: 
    - community.vmware
  gather_facts: false
  vars:
    esxi_password: '{{ lab_password }}'
    vcenter_password: '{{ lab_password }}'    
    vcenter_fqdn: "{{ vcenter_hostname }}.{{ lab_domain }}"
    vcenter_net_prefix: '{{ lab_netmask_cidr }}'
    vcenter_gateway: '{{ lab_gateway }}'
    dns_servers: '{{ dc_address }}'
    domain: '{{ lab_domain }}'
    searchpath: ""
  vars_files: 
    vars.yml
  tasks:
  - vmware_deploy_ovf:
      hostname: '{{ esxi_address }}'
      username: '{{ esxi_username }}'
      password: '{{ esxi_password }}'
      name: '{{ vcenter_hostname }}' # shortname, not FQDN
      ovf: '{{ files_path }}/{{ vcenter_ova }}' 
      disk_provisioning: thin
      networks:
          "Network 1": "{{vm_network}}"
      wait_for_ip_address: true
      validate_certs: no
      inject_ovf_env: true
      properties:
        DeploymentOption.value: 'tiny' # vCenter t-shirt size: tiny,small,medium,large, or infrastructure 
        guestinfo.cis.appliance.net.addr.family: 'ipv4' # ipv4 or ipv6
        guestinfo.cis.appliance.net.mode: 'static' # static or dhcp
        guestinfo.cis.appliance.net.addr: '{{ vcenter_address }}' 
        guestinfo.cis.appliance.net.pnid: '{{ vcenter_address }}' # "{{ vcenter_hostname }}.{{ domain }}" # FQDN of vcenter server
        guestinfo.cis.appliance.net.prefix: '{{ vcenter_net_prefix }}' # netmask length, CIDR notation, i.e. '24'
        guestinfo.cis.appliance.net.gateway: '{{ vcenter_gateway }}' 
        guestinfo.cis.appliance.net.dns.servers: '{{ dns_servers }}' # Comma separated list of IP addresses of DNS servers.
        guestinfo.cis.appliance.root.passwd: '{{ vcenter_password }}' 
        guestinfo.cis.deployment.autoconfig: 'True' # Auto-configure after deployment
        guestinfo.cis.vmdir.password: '{{ vcenter_password }}' # SSO Password for administrator@vsphere.local
        guestinfo.cis.upgrade.import.directory: "/storage/seat/cis-export-folder" #FIX for VCSA 8.0
        domain: '{{ domain }}'
        searchpath: '{{ searchpath }}'
    delegate_to: localhost
  - name: Wait for vCenter
    vmware_about_info:
      hostname: '{{ vcenter_address }}'
      username: 'administrator@vsphere.local'
      password: '{{ vcenter_password }}'
      validate_certs: no
    delegate_to: localhost
    retries: 30
    delay: 60
    register: result           
    until: result is succeeded 